# Generated by Django 3.0.5 on 2020-04-28 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)])),
                ('c_firstname', models.CharField(max_length=30)),
                ('c_lastname', models.CharField(max_length=30)),
                ('c_street', models.CharField(max_length=30)),
                ('c_city', models.CharField(max_length=30)),
            ],
        ),
    ]
