# Generated by Django 3.0.5 on 2020-04-30 05:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import insurancesys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numeric characters are allowed.'), django.core.validators.MinLengthValidator(10)])),
                ('c_firstname', models.CharField(max_length=30)),
                ('c_lastname', models.CharField(max_length=30)),
                ('c_street', models.CharField(max_length=30)),
                ('c_city', models.CharField(max_length=30)),
                ('c_state', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]+$', 'Only uppercase characters are allowed.'), django.core.validators.MinLengthValidator(2)])),
                ('c_zipcode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numeric characters are allowed.'), django.core.validators.MinLengthValidator(5)])),
                ('c_gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1)),
                ('c_maritalstatus', models.CharField(choices=[('S', 'single'), ('M', 'married'), ('W', 'widow or widower')], max_length=1)),
                ('c_customertype', models.CharField(choices=[('A', 'auto policy customer'), ('H', 'home policy customer'), ('AH', 'auto & home policy customer')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numeric characters are allowed.'), django.core.validators.MinLengthValidator(15)])),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=22)),
                ('payment_due', models.DateField()),
                ('installment', models.CharField(choices=[('Y', 'Pay by Installment'), ('N', 'Full Payment')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numeric characters are allowed.'), django.core.validators.MinLengthValidator(12)])),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=22)),
                ('policy_status', models.CharField(choices=[('C', 'policy is current'), ('P', 'policy is expired')], max_length=1)),
                ('policy_type', models.CharField(choices=[('A', 'auto policy'), ('H', 'home policy')], max_length=1)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancesys.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numeric characters are allowed.'), django.core.validators.MinLengthValidator(12)])),
                ('model_year', models.IntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=insurancesys.models.current_year, verbose_name='make_model_year')),
                ('vehiclestatus', models.CharField(choices=[('L', 'vehicle is leased'), ('F', 'vehicle is financed'), ('O', 'vehicle is owned')], max_length=1)),
                ('policys', models.ManyToManyField(to='insurancesys.Policy')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numeric characters are allowed.'), django.core.validators.MinLengthValidator(15)])),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CKECK', 'pay with check'), ('PAYPAL', 'pay with paypal'), ('CREDIT', 'pay with credit card'), ('DEBIT', 'pay with debit card')], max_length=6)),
                ('pay_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=22)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancesys.Invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='policy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancesys.Policy'),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('home_id', models.CharField(max_length=14, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numeric characters are allowed.'), django.core.validators.MinLengthValidator(14)])),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=22)),
                ('homearea', models.DecimalField(decimal_places=2, max_digits=22)),
                ('hometype', models.CharField(choices=[('S', 'single family'), ('M', 'multi family'), ('C', 'condominium'), ('T', 'town house')], max_length=1)),
                ('auto_fire_notification', models.CharField(choices=[('1', 'yes'), ('0', 'no')], max_length=1)),
                ('home_security_system', models.CharField(choices=[('1', 'yes'), ('0', 'no')], max_length=1)),
                ('swimming_pool', models.CharField(choices=[('U', 'underground swimming pool'), ('O', 'overground swimming pool'), ('I', 'indoor swimming pool'), ('M', 'multiple swimming pool'), ('N', 'no swmming pool')], max_length=1)),
                ('basement', models.CharField(choices=[('1', 'yes'), ('0', 'no')], max_length=1)),
                ('policys', models.ManyToManyField(to='insurancesys.Policy')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_licence', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numeric characters are allowed.'), django.core.validators.MinLengthValidator(15)])),
                ('d_firstname', models.CharField(max_length=30)),
                ('d_lastname', models.CharField(max_length=30)),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancesys.Vehicle')),
            ],
        ),
    ]
