# Generated by Django 3.0.5 on 2020-04-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_customertype',
            field=models.CharField(choices=[('A', 'auto insurance customer'), ('H', 'home insurance customer'), ('AH', 'auto & home insurance customer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_type',
            field=models.CharField(choices=[('A', 'auto insurance'), ('H', 'home insurance')], max_length=1),
        ),
    ]
