# Generated by Django 3.0.5 on 2020-05-01 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='d_birthdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
