# Generated by Django 3.0.5 on 2020-04-28 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesys', '0002_auto_20200428_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
