# Generated by Django 3.0.5 on 2020-05-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesys', '0003_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='c_birthdate',
            field=models.DateField(default='2020-05-01'),
            preserve_default=False,
        ),
    ]
