# Generated by Django 3.0.5 on 2020-05-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesys', '0004_customer_c_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='incoice_cleared',
            field=models.BooleanField(default=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_status',
            field=models.CharField(choices=[('C', 'policy is current'), ('P', 'policy is expired'), ('PD', 'policy is pending payment')], max_length=2),
        ),
    ]
