# Generated by Django 3.0.5 on 2020-05-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesys', '0006_auto_20200501_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='incoice_cleared',
            new_name='invoice_cleared',
        ),
        migrations.AlterField(
            model_name='home',
            name='auto_fire_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='home',
            name='basement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_security_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='installment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
